<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MediaPlayer"
    nsURI="http:///org/jamp/model/player/media.ecore" nsPrefix="org.jamp.model.player">
  <eClassifiers xsi:type="ecore:EClass" name="Playlist">
    <eOperations name="shuffle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediaList" upperBound="-1"
        eType="#//MediaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="album" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaApi" abstract="true" interface="true">
    <eOperations name="init"/>
    <eOperations name="play">
      <eParameters name="playMe" eType="#//MediaObject"/>
    </eOperations>
    <eOperations name="pause">
      <eParameters name="pauseMe" eType="#//MediaObject"/>
    </eOperations>
    <eOperations name="stop">
      <eParameters name="stopMe" eType="#//MediaObject"/>
    </eOperations>
    <eOperations name="dispose"/>
    <eOperations name="canPlay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="media" eType="#//MediaObject"/>
    </eOperations>
    <eOperations name="updateMediaObjectInfo">
      <eParameters name="updateMe" eType="#//MediaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyPlaying" upperBound="-1"
        eType="#//MediaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyPaused" upperBound="-1"
        eType="#//MediaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="PLAYING" literal="playing"/>
    <eLiterals name="PAUSED" value="1" literal="paused"/>
    <eLiterals name="STOPPED" value="2" literal="stopped"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayLayer">
    <eOperations name="registerApi">
      <eParameters name="addMe" eType="#//MediaApi"/>
    </eOperations>
    <eOperations name="unregisterApi">
      <eParameters name="unregisterMe" eType="#//MediaApi"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="installedApi" upperBound="-1"
        eType="#//MediaApi"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="myLibrary" eType="#//Library"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediaLibrary" upperBound="-1"
        eType="#//MediaObject" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
